apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: junior-full-access
  namespace: test
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: junior-full-access-binding
  namespace: test
subjects:
- kind: Group
  name: junior
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: junior-full-access
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: junior-read-only
  namespace: production
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: junior-read-only-binding
  namespace: production
subjects:
- kind: Group
  name: junior
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: junior-read-only
  apiGroup: rbac.authorization.k8s.io 